"""Build policy pages: public contact email, then optional page slugs to rebuild."""
from pathlib import Path
import html
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
EMAIL = sys.argv[1] if len(sys.argv) > 1 else ""
if not re.fullmatch(r"[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+", EMAIL):
    raise SystemExit("Provide a valid public contact email.")
EMAIL = html.escape(EMAIL, quote=True)
CONTACT = f'<a href="mailto:{EMAIL}">{EMAIL}</a>'
DATE = "September 16, 2026"

PAGES = {
"lyra": ("Lyra Personal Assistant", f"""
<nav aria-label="Lyra information"><a href="/lyra/">About Lyra</a> · <a href="/lyra/privacy/">Lyra privacy policy</a> · <a href="/lyra/terms/">Lyra terms of use</a></nav>
<p class="policy-summary">Lyra is Tristan Merson's private personal assistant for planning, preparation, reminders, and following through on authorized work. This is an information page, not a public registration or email-login service.</p>
<h2>What the Google connection is for</h2><p>After activation through Lyra's existing controller, the email tools support bounded message listing, reading available plain text, creating new plain-text drafts, and sending new plain-text messages to recipients specified through authenticated owner instructions. Calendar access supports the owner's separate, existing planning and calendar workflow. Attachments, HTML browsing, changes to existing drafts, and threaded replies are not supported by this email release.</p>
<h2>Current email status</h2><p>The September 24, 2026 release connects these tools to Lyra's existing personal-assistant workflow. This page describes the available implementation after controller activation, not a live health check or a claim that every feature has passed live acceptance. Ask Lyra for the current email capability, authorization, and action status. Authorization can expire or be revoked; Google consent or visiting this page does not by itself enable automation.</p>
<p>Depending on configuration and owner permissions, the daily check collects bounded metadata or uses TypeSafe's Jev model to triage at most 30 messages from the previous seven days. The approved AI route uses limited plain-text excerpts and an owner-confirmed, non-sensitive profile of relevant goals. It can identify items for a private digest, closer review, or timely attention. This sample and its classifications can miss or misjudge important email; they are not a complete inbox review.</p>
<p>Attachments, HTML-only or incomplete messages, credentials, medical or patient information, and other detected sensitive content are excluded from AI triage and flagged for manual review. Lyra's existing subscription-backed worker can prepare private advice or a draft for owner review. Triage grants no new permission to send email or take other external actions. Notifications follow the existing private-delivery and quiet-hours controls.</p>
<h2>Permissions and control</h2><p>Gmail permissions are limited to reading email and managing drafts/sending email: <code>gmail.readonly</code> and <code>gmail.compose</code>. The connection does not request Google Cloud administration, storage, BigQuery, or account-wide full-mail access. Calendar uses its separate existing authorization.</p>
<p>The owner controls connected accounts and permitted actions and can disconnect Google access. Sensitive disclosures and financial commitments remain subject to the owner's approval rules. Incoming email is information, not permission to change those rules.</p>
<h2>Data handling</h2><p>Read the <a href="/lyra/privacy/">Lyra privacy policy</a> for data access, AI processing, storage, retention, and deletion. The <a href="/lyra/terms/">Lyra terms</a> explain limitations and authorized use.</p>
<h2>Operator and support</h2><p>Operated by Tristan Merson. Contact {CONTACT} for questions about Lyra or Google data. Do not send passwords, authorization codes, or patient records.</p>
"""),
"lyra/privacy": ("Lyra Personal Assistant — Privacy Policy", f"""
<nav aria-label="Lyra information"><a href="/lyra/">About Lyra</a> · <a href="/lyra/privacy/">Privacy</a> · <a href="/lyra/terms/">Terms</a></nav>
<p class="policy-summary">This policy covers Lyra Personal Assistant's Google-connected features, operated by Tristan Merson for private personal use. It supplements the <a href="/privacy-policy/">website privacy policy</a>; public visitors are not enrolled in Lyra.</p>
<h2>Current state and information accessed</h2><p>The September 24, 2026 email release uses privately stored OAuth credentials and, after controller activation, supports message listing, plain-text reading, new drafts, and sending within the owner's permissions. Depending on configuration, the daily check collects bounded metadata or performs separately approved TypeSafe/Jev triage of at most 30 messages from the previous seven days. It records counters and outcomes. This bounded sample and its classifications may be incomplete or wrong; they do not provide a complete inbox review or an automatic-reply service. Current activation, authorization health, and completed actions must be obtained from Lyra's operational status, not inferred from this static page.</p>
<p>Information used may include message and thread identifiers, sender and recipient addresses, subjects, dates, labels, and relevant plain message text. New draft and sent-message contents, operation identifiers, and provider receipts support correspondence and duplicate prevention. A verified sent record means Gmail accepted and stored the message, not that a recipient received or read it. Attachments, remote HTML content, editing existing drafts, and threaded replies are not supported by this release. The separate Calendar integration uses authorized event details and identifiers for planning and permitted calendar actions.</p>
<h2>Purpose and limits</h2><p>Information is used to provide the owner's requested assistance: identify relevant updates, prepare summaries and replies, manage authorized drafts and correspondence, plan work, and record progress without duplicate actions. Access is not permission to use email for unrelated purposes. Lyra does not sell Google data, use it for advertising, or use it to determine creditworthiness.</p>
<p>Google data is handled under the <a href="https://developers.google.com/terms/api-services-user-data-policy">Google API Services User Data Policy</a> and its Limited Use requirements. Google data must not be used to train or improve generalized AI or machine-learning models.</p>
<h2>AI processing, providers, and disclosure</h2><p>When its permission and data-use gate allows email assistance, selected message text and task context can be processed through Lyra's existing OpenAI conversational route. On September 24, 2026, the owner confirmed that the connected mailbox is personal-only and that OpenAI's &ldquo;Improve the model for everyone&rdquo; setting was turned off. This records the owner's confirmation, not an independent audit of the signed-in dashboard or every provider setting. If those conditions change, email-content processing must be paused and reassessed.</p>
<p>The owner has separately approved sending limited personal-email excerpts and a confirmed, non-sensitive profile of relevant goals to TypeSafe's Jev model for bounded triage. This route operates only while its explicit transfer permission and mailbox and model-data-use gates remain enabled. Credentials, medical or patient information, other detected sensitive content, attachments, HTML-only messages, and incomplete message content are excluded from provider processing by this triage workflow and flagged for manual review. Screening and classification are safeguards, not guarantees that every sensitive or important message will be recognized.</p>
<p>TypeSafe's <a href="https://typesafe.ai/legal/privacy-policy">privacy policy</a> states that it does not train or fine-tune models on supplied inputs. Its <a href="https://docs.typesafe.ai/legal">legal documentation</a> describes zero data retention as a separate enterprise option. This integration uses standard provider retention; zero data retention has not been established. Inputs and related service records may therefore be retained under TypeSafe's applicable policies. A no-training commitment does not mean no retention.</p>
<p>When a message needs closer attention, Lyra's existing subscription-backed OpenAI worker may receive a limited excerpt and relevant task context to prepare private advice or a draft for owner review. This handoff grants no new authority to send email, change a mailbox or calendar, make purchases, or take other external actions. Notifications use existing private-delivery and quiet-hours controls. The metadata-only check does not send email content to Jev. No claim is made that AI processing stays on the owner's devices; further processing routes require disclosure and the appropriate permission before activation.</p>
<p>Google provides Gmail and Calendar. The owner's private server hosts the integration and its records. If private notifications are enabled, selected summaries or results may be delivered through the owner's connected Discord account. Sending an authorized email necessarily discloses its contents and addressing information to its recipients and their mail providers. Gmail content is not published to this website. No other data transfer is authorized by this notice; legally required disclosures and security investigations may be necessary.</p>
<h2>Storage, retention, and protection</h2><p>OAuth tokens are stored in access-restricted files on the private server, not in this public website or its source repository. The integration uses encrypted transport to Google and the model providers. Routine raw message bodies used for daily triage are handled transiently and are not copied into Lyra's general-purpose fact memory. Local triage audit records retain request hashes, byte counts, question identifiers, typed classifications, and usage rather than raw email excerpts.</p>
<p>For messages escalated to the worker, limited excerpts may be retained as private task evidence and in associated model-session transcripts. Those records are distinct from general-purpose memory. Operational identifiers, prepared advice or drafts, artifacts, and action receipts may also be retained for continuity, verification, and duplicate prevention. There is not currently an automatic deletion schedule for those private records. Retention is reviewed during owner-directed maintenance and verified deletion requests; necessary security or legal records may be retained with an explanation.</p>
<p>Provider logs and backups follow their actual provider settings and retention practices; this policy does not promise immediate deletion from every backup. Access controls reduce risk but do not guarantee absolute security. This assistant is not intended for patient or healthcare records.</p>
<h2>Your choices and deletion requests</h2><p>The owner can disable the integration or remove Lyra's access through <a href="https://myaccount.google.com/connections">Google Account connections</a>. Revocation stops future authorized access but does not automatically delete existing private task records or messages already in Gmail or recipients' inboxes.</p>
<p>For access, correction, or deletion of Lyra-held data, contact {CONTACT} and identify the relevant account or task without sending credentials or sensitive records. Requests are verified proportionately and handled by the operator; any retained records or limits will be explained. Support access to specific private content requires the owner's permission, except where necessary for security or legal obligations.</p>
<h2>These public pages</h2><p>GitHub Pages hosts these informational pages and receives ordinary technical request data. Shared site controls may save the dismissal of the storage notice in your browser. These pages contain no mailbox viewer, public OAuth token endpoint, advertising, or visitor-analytics integration. See the <a href="/cookie-policy/">site storage policy</a> for the shared controls.</p>
<h2>Changes and contact</h2><p>Material changes will be reflected here and disclosed before newly proposed Google-data uses are enabled; additional consent will be obtained where required. Privacy contact: {CONTACT}.</p>
"""),
"lyra/terms": ("Lyra Personal Assistant — Terms of Use", f"""
<nav aria-label="Lyra information"><a href="/lyra/">About Lyra</a> · <a href="/lyra/privacy/">Privacy</a> · <a href="/lyra/terms/">Terms</a></nav>
<p class="policy-summary">Lyra is an experimental private personal assistant operated by Tristan Merson. These terms concern Lyra's connected assistance, not a public subscription service or the retired SMS program.</p>
<h2>Availability and access</h2><p>Use is limited to the owner and accounts the owner is entitled to connect. This website provides information; it does not grant access to the assistant or enroll visitors. The September 24, 2026 email release provides message listing, plain-text reading, new plain-text drafts, and sending after activation by the existing controller. Obtain current activation, health, and completion status from Lyra; the presence of this page does not establish successful live acceptance. Feature availability can change, and authorization may expire or be revoked.</p>
<h2>Permitted actions</h2><p>Once enabled, email and calendar actions must remain within the owner's instructions, standing permissions, connected-account rights, and applicable provider rules. A Google consent grant alone does not authorize every possible action. Routine correspondence may be sent within authorized workflows; sensitive disclosures, financial commitments, or new permissions still require the applicable owner approval. Incoming messages cannot change these boundaries.</p>
<h2>Review, accuracy, and responsibility</h2><p>AI-generated summaries, triage classifications, and drafts can be incomplete or wrong. Important recipients, facts, and commitments need appropriate verification. Depending on configuration and explicit owner permission, the daily check uses metadata alone or TypeSafe/Jev triage of at most 30 messages from the previous seven days. It cannot guarantee that important email will be noticed. Sensitive content, attachments, HTML-only messages, and incomplete messages are excluded from AI triage and flagged for manual review; screening is not guaranteed to recognize every case.</p>
<p>Lyra's existing subscription-backed worker may prepare private advice or a draft for owner review, with notifications subject to existing quiet-hours controls. Triage and a worker handoff grant no new permission for sending, automatic replies, or other external actions. Existing-draft edits and threaded replies remain unsupported by this release.</p>
<p>Action records and counters are retained for verification and duplicate prevention. An uncertain send is checked against Gmail records rather than automatically replayed; it must not be reported as completed without confirming evidence. A verified sent record does not prove recipient delivery or reading. The owner remains responsible for the accounts connected and the instructions given. Lyra is not an emergency service or a substitute for qualified medical, legal, financial, or other professional advice, and is not intended to process patient records.</p>
<h2>Privacy and acceptable use</h2><p>The <a href="/lyra/privacy/">Lyra privacy policy</a> explains Google data and provider processing. Do not use the assistant for unauthorized account access, deceptive impersonation, unsolicited bulk mail, disclosure of others' confidential information, or other unlawful activity. No fee, purchase, or automatic renewal is created by visiting these pages or granting Google consent.</p>
<h2>Stopping access and service limitations</h2><p>The owner can stop a workflow, disconnect an account, or revoke Google access. Disconnecting cannot undo a delivered email or remove a recipient's copy. Availability, delivery, and error-free operation are not guaranteed; failures should be reported and reconciled rather than treated as completed work. Nothing here excludes rights that applicable law does not allow to be excluded.</p>
<h2>Changes and support</h2><p>These terms will be updated when the supported service changes. Material changes to data use or permissions require the corresponding disclosure and consent. Questions: {CONTACT}.</p>
"""),
"privacy-policy": ("Privacy policy", f"""
<p class="policy-summary">This policy covers Tristan Merson’s personal website, accounts, shop catalog, games, and photo gallery.</p>
<h2>Who operates this site</h2><p>Tristan Merson operates tristans-website.com. For privacy questions and requests, contact {CONTACT} or visit <a href="/privacy-requests/">Privacy requests</a>.</p>
<h2>What information is used</h2><ul>
<li><strong>Visiting:</strong> the hosting and infrastructure providers receive technical request information, such as your IP address, browser information, and requested URLs, to deliver and protect the site.</li>
<li><strong>Accounts:</strong> Supabase processes your email, authentication credentials, account identifier, and sign-in information. A nickname is optional. Account creation records the version and time of your terms acceptance and your age eligibility declaration. Do not use a real name if you prefer an alias.</li>
<li><strong>Profile:</strong> an optional display name, bio, and image URL are stored with your account. Avoid adding sensitive or medical information. Previewing a remotely hosted image sends a request to that image’s host.</li>
<li><strong>Games:</strong> dice-game progress is saved in this browser. When you are signed in, completed dice runs are saved to your account automatically; you can also save your current score manually. Saved records include your account identifier, chosen nickname, score, game mode, and submission time. These scores appear in your account history and are not added to the public leaderboard by the account-saving feature. Guests can separately choose to publish a nickname and score to the public leaderboard. Public entries can be seen and copied by other visitors. To play without saving account scores, sign out first.</li>
<li><strong>Shop:</strong> product selections and quantities are saved in this browser’s cart. There is no checkout, payment collection, shipping-address collection, or order placement on this site.</li>
<li><strong>Contact:</strong> if you email Tristan, your address, message, and any information you send are used to handle your request. The privacy-request helper only prepares an email draft; it does not submit a request by itself.</li></ul>
<h2>Why this information is used</h2><p>Information supports the features you request, account access, saved game records, public scores you choose to share, responses to inquiries, and site security. Required account information is separate from optional profile fields. Creating an account does not subscribe you to marketing.</p>
<h2>Providers and public content</h2><p>GitHub Pages hosts the website. Supabase provides account, profile, catalog, and game databases; the public leaderboard uses a separate Supabase project. Product and profile images can be served by external image hosts, which receive the technical request information needed to load them. The Supabase browser library is served from this website.</p><p>Provider information: <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub privacy statement</a> and <a href="https://supabase.com/privacy">Supabase privacy policy</a>. Providers may process data in countries other than yours. Public gallery photos and public leaderboard entries are visible without an account.</p>
<h2>Cookies, browser storage, and tracking</h2><p>This site does not include advertising trackers or visitor-analytics scripts. It uses browser storage for sign-in sessions, the local cart, game progress, and remembering a dismissed storage notice. See the <a href="/cookie-policy/">cookie and storage policy</a> for details and controls.</p>
<h2>Retention and security</h2><p>Account and game records are retained while used for these features, until removed through a verified request or site maintenance, subject to any records that must be retained for legal or security reasons. There is no automatic account-expiration schedule. Hosting logs and backups follow the relevant providers’ retention practices. Browser data remains until you clear it, sign out where applicable, or the browser removes it.</p><p>Access controls are used to limit account-data access. No online service can guarantee absolute security. Please do not send passwords, government identification, payment-card details, or medical records with a request.</p>
<h2>Your choices and requests</h2><p>You can edit optional profile fields, sign out, clear local browser data, or request access, correction, or deletion. Email from the address associated with your account when possible. For a public score, identify the nickname and approximate submission date; additional verification may be needed because public entries are not linked to an account. Deleting browser storage does not delete server records.</p><p>Depending on your location, you may have additional rights, including objection, restriction, portability, or a complaint to a privacy regulator. Requests are reviewed according to applicable law. If a record must be retained or a request cannot be verified, Tristan will explain the issue in the response.</p>
<h2>Children</h2><p>Accounts and public score submissions are for people age 13 or older. Please do not create an account or submit personal information if you are under 13. The site does not offer a parental-consent process. If you believe a child’s personal information has been submitted, contact {CONTACT} to request review and removal.</p>
<h2>Changes to this policy</h2><p>Changes to this policy will be posted here with an updated date.</p>
"""),
"terms-and-conditions": ("Terms of use", f"""
<p class="policy-summary">These terms describe use of Tristan Merson’s personal website and its current tools.</p>
<h2>The site and its tools</h2><p>The site includes personal information, a travel gallery, creative and game tools, optional accounts, and a shop catalog. Tools are provided for personal use and entertainment. Availability and functionality can change.</p><p>The site is not a healthcare service. Personal references to nursing do not create a clinician–patient relationship. Do not use the site or its contact inbox for medical advice or emergency care.</p>
<h2>Accounts and eligibility</h2><p>You must be at least 13 to create an account or submit a public score. Keep your sign-in details secure, provide an email you control, and use only your own account. You can use an alias and leave optional profile fields blank. If you are not old enough to enter an agreement where you live, involve a parent or guardian before using account features.</p>
<h2>Acceptable use</h2><p>Do not use the site for unlawful activity, impersonation, harassment, spam, unauthorized access, or interference with other users or the site. Do not submit someone else’s private information or content you do not have permission to share. Access may be restricted for misuse.</p>
<h2>Public and private game scores</h2><p>Guest leaderboard submissions are public when you choose to publish them. Account score history is private to the account in the site interface. The game is an experiment; leaderboard scores are not verified competition results and have no cash value or prizes. Do not put contact details or other personal information in a public nickname.</p>
<h2>Catalog, prices, and refunds</h2><p>The shop is a catalog preview. Saving items to the local cart does not place an order, reserve inventory, or authorize a charge. Displayed numeric prices are in US dollars. No payment, shipping charge, tax, subscription, or other fee is collected through this site. See the <a href="/refund-policy/">refund and purchasing policy</a>.</p>
<h2>Content and third-party materials</h2><p>Respect applicable copyrights and other rights. Third-party names and materials remain subject to their owners’ rights; their appearance does not imply endorsement or a license to reuse them. You retain your rights in material you submit and authorize the processing and display needed for the feature you select, including public display of a score you choose to publish. See <a href="/credits/">credits and content information</a>.</p>
<h2>Availability and responsibility</h2><p>Experimental tools may contain errors, lose progress, or be unavailable. Use your own judgment and keep any important information elsewhere. Nothing in these terms excludes rights, remedies, or responsibilities that applicable law does not allow to be excluded.</p>
<h2>Privacy, account closure, and contact</h2><p>The <a href="/privacy-policy/">privacy policy</a> explains how information is handled. You can ask to close an account or remove information through <a href="/privacy-requests/">Privacy requests</a>. Contact the operator, Tristan Merson, at {CONTACT}.</p>
<h2>Updates</h2><p>Revised terms will be posted here with an updated date. New paid services, if offered later, will need their own clearly stated purchasing terms before an order is accepted.</p>
"""),
"refund-policy": ("Refund and purchasing policy", f"""
<p class="policy-summary">The shop is currently a catalog only. This website does not accept orders or payments.</p>
<h2>Cart and prices</h2><p>Adding an item to your cart saves a selection in this browser. It does not create an order, reserve a product, or charge you. Numeric catalog prices are shown in US dollars and are preview information, not a final checkout total. No recurring billing or paid subscription is offered.</p>
<h2>Refunds and unexpected charges</h2><p>There are no website purchase payments to refund. If you see a charge you believe relates to this site, contact {CONTACT} with the date and a brief description so it can be investigated. Do not email card numbers or banking passwords. A transaction made through a separate seller or platform must be handled through that seller’s process and applicable consumer rights.</p>
<h2>Before any future sales</h2><p>If purchasing is introduced, the applicable seller details, complete costs, delivery information, cancellation and return conditions, and refund process must be displayed before you commit to an order. This page does not waive any consumer rights provided by law.</p>
"""),
"cookie-policy": ("Cookies and browser storage", """
<p class="policy-summary">No advertising or analytics cookies are added by this site. Browser storage supports features you choose to use. There are no optional tracking categories to accept.</p>
<h2>What is stored</h2><ul>
<li><strong>Sign-in session:</strong> Supabase stores authentication tokens under <code>sb-azuixkurdzbvgsnuotkr-auth-token</code> and related keys, so you can stay signed in. Signing out removes the local session. A token from the previous leaderboard project may also exist in older browsers.</li>
<li><strong>Local cart:</strong> <code>tristan-merson-storefront-cart-v1</code> holds product identifiers, names, prices, and quantities after you change your cart. It is not an order.</li>
<li><strong>Game progress:</strong> <code>diceGameProgression</code> holds dice-game progression in this browser.</li>
<li><strong>Storage notice:</strong> <code>tristan-storage-notice-v1</code> records when you dismiss the notice. The notice is shown again after 180 days. This records dismissal, not consent to tracking.</li></ul>
<p>Cart and game storage have no automatic expiration. Sign-in data can remain until sign-out or browser clearing, subject to authentication expiry. Your browser may remove stored data sooner. GitHub and Supabase also receive technical requests to host and protect their services; that processing is separate from browser storage.</p>
<h2>Your controls</h2><p>You can browse without an account, sign out, reset game progress in the game, remove cart items, or clear saved site data below. Your browser’s privacy settings also control local storage and cookies. Blocking storage may prevent sign-in persistence and saved progress.</p>
<form id="clear-browser-data-form">
<label><input type="checkbox" required><span>I understand this removes saved sign-in details, the cart, and dice-game progress from this browser. It does not delete my account or server records.</span></label>
<button type="submit">Clear this browser’s saved site data</button>
<p id="clear-browser-data-status" role="status"></p></form>
<p>For account or server-data deletion, use <a href="/privacy-requests/">Privacy requests</a>. Close other tabs for this site before clearing data so they do not save old state again.</p>
<h2>Changes to tracking</h2><p>If optional tracking is added later, this notice and the controls must be updated before it is enabled. Dismissing today’s notice does not authorize future tracking.</p>
"""),
"privacy-requests": ("Privacy and deletion requests", f"""
<p class="policy-summary">To request access, correction, or deletion of your information, email {CONTACT}. You do not need to sign in to make a request.</p>
<h2>What to include</h2><p>Describe the request and, if possible, write from the email address associated with your account. For public leaderboard entries, give the nickname, approximate date, and score. For a gallery photo, include its page or description. Do not send a password, identification document, financial information, or medical records.</p>
<p>Tristan may ask for proportionate information to verify that the records relate to you. Some records may need to be retained for legal or security reasons; if that affects your request, the response will explain it. Public copies made by other people may be outside the site operator’s control.</p>
<h2>Prepare an email</h2><p>This optional helper prepares a draft on your device. You must send it through your email app. No request is submitted or stored by this form.</p>
<form id="privacy-request-form" data-contact="{EMAIL}">
<label for="request-type">Request type<select id="request-type"><option>Delete my account and related personal data</option><option>Delete a public leaderboard entry</option><option>Access a copy of my data</option><option>Correct my information</option><option>Remove a photo involving me</option><option>Other privacy request</option></select></label>
<label for="request-reference">Relevant nickname or page (optional)<input id="request-reference" maxlength="250" autocomplete="off"></label>
<button type="submit">Prepare email draft</button>
<p id="privacy-request-status" role="status"></p><a id="privacy-email-draft" href="mailto:{EMAIL}" hidden>Open draft in email app</a>
</form>
<noscript><p>Email {CONTACT} directly with the request you want to make.</p></noscript>
<h2>Browser data is separate</h2><p><a href="/cookie-policy/">Clear this browser’s stored data</a> to remove saved sign-in details, cart, and game progress. This does not submit a deletion request or remove the account and server records.</p>
"""),
"contact": ("Contact and site details", f"""
<p class="policy-summary">This personal website is operated by Tristan Merson.</p>
<p><strong>Website:</strong> tristans-website.com<br><strong>Contact:</strong> {CONTACT}</p>
<h2>Get in touch</h2><p>Use the email above for site questions, accessibility problems, content permissions, and catalog questions. The shop currently accepts no orders or payments.</p>
<p>For access, correction, or deletion of personal information, see <a href="/privacy-requests/">Privacy requests</a>. Please avoid sending sensitive information.</p>
<h2>Messages and subscriptions</h2><p>The site has no newsletter or marketing-email sign-up. Account confirmation and password-reset emails support actions you request; creating an account is not marketing consent. See <a href="/communications/">email preferences</a> for help with unwanted messages.</p>
<h2>Healthcare questions</h2><p>This is a personal and creative-project website, not a healthcare service. This inbox is not for medical advice or emergencies.</p>
"""),
"communications": ("Email preferences", f"""
<p class="policy-summary">There is currently no newsletter or marketing mailing list on this website.</p>
<h2>Account emails</h2><p>You may receive account confirmation or password-reset emails when those actions are requested. Those messages support access to your account. They do not enroll you in marketing.</p>
<h2>Unwanted messages</h2><p>If you received a message you did not request, contact {CONTACT} with a brief description. Do not forward passwords or sign-in links. To ask to close an account, use <a href="/privacy-requests/">Privacy requests</a>.</p>
<h2>Future marketing</h2><p>If marketing email is introduced, it will need a clearly identified sender and a working unsubscribe process. No marketing permission is collected through the current account form.</p>
"""),
"accessibility": ("Accessibility", f"""
<p class="policy-summary">The site is being improved so more people can browse and use its tools with a keyboard, screen reader, or browser zoom.</p>
<h2>Features</h2><p>Pages include skip links, visible keyboard focus, labeled form fields, and policy links. Photo-viewer controls support keyboard operation. Shared styles respect a reduced-motion preference.</p>
<h2>Report a barrier</h2><p>Email {CONTACT} with the page and the task you were trying to complete. If useful, include your browser and assistive technology; do not send medical information. You can request an alternative way to access content.</p>
<h2>Ongoing review</h2><p>Accessibility work is ongoing. This statement is not a claim that every page, third-party image, document, or future catalog entry conforms to an accessibility standard. Some older creative content and documents may still need improvements.</p>
"""),
"credits": ("Credits and content information", f"""
<h2>Site and photos</h2><p>The site presents Tristan Merson’s projects and a personal Japan-trip gallery. To ask about an image, request a correction, or request removal of a photo involving you, contact {CONTACT}. Public display does not grant permission to reuse an image.</p>
<h2>Software and fonts</h2><p>The site uses the open-source Supabase JavaScript library under its MIT license. The pinned version, notices, and source information are included in the <a href="https://github.com/tristantheguy/website/tree/main/assets/vendor">website repository</a>. Text uses fonts installed on your device; the site does not download web fonts.</p>
<h2>Creative references</h2><p>The existing magical-effects collection and its accompanying document credit <em>The Net Libram of Random Magical Effects</em>, version 1.20, by Orrex. Character and game references belong to their respective rights holders. Attribution is not a grant of permission or a statement of endorsement.</p>
<p>If you own rights in material on this site and want to discuss its use or removal, email the contact above with enough detail to identify the material.</p>
"""),
}

selected = set(sys.argv[2:])
if selected - PAGES.keys():
    raise SystemExit("Unknown page slug; no pages written.")
for slug, (title, body) in PAGES.items():
    if selected and slug not in selected:
        continue
    destination = ROOT / slug / "index.html"
    destination.parent.mkdir(parents=True, exist_ok=True)
    date = "September 24, 2026" if slug == "lyra" or slug.startswith("lyra/") else DATE
    destination.write_text(f'''<!doctype html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="{html.escape(title)} for Tristan Merson’s personal website.">
<meta name="referrer" content="no-referrer">
<title>{title} | Tristan Merson</title>
<link rel="canonical" href="https://tristans-website.com/{slug}/">
<link rel="stylesheet" href="/site-ui.css"><script src="/site-ui.js" defer></script>
</head><body class="policy-body">
<header class="policy-header"><a href="/">Tristan Merson</a><nav aria-label="Primary"><a href="/shop.html">Shop</a> · <a href="/account.html">Account</a> · <a href="/contact/">Contact</a></nav></header>
<main id="main-content" class="policy-main" tabindex="-1"><h1>{title}</h1><p class="policy-date">Last updated: {date}</p>{body}</main>
</body></html>
''', encoding="utf-8")

if selected:
    print(f"Built {len(selected)} selected pages; unrelated and legacy pages unchanged.")
    raise SystemExit(0)

for slug in ["privacy-policy", "terms-and-conditions"]:
    (ROOT / (slug + ".html")).write_text(f'''<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0; url=/{slug}/"><link rel="canonical" href="https://tristans-website.com/{slug}/"><title>Policy page moved</title></head><body><main><h1>Policy page moved</h1><p><a href="/{slug}/">Read the current {PAGES[slug][0].lower()}</a>.</p></main></body></html>''', encoding="utf-8")
    (ROOT / (slug + ".md")).write_text(f'# {PAGES[slug][0]}\n\nThe current policy is maintained at [{slug}/index.html]({slug}/index.html) and published at https://tristans-website.com/{slug}/.\n', encoding="utf-8")

(ROOT / "sms-opt-in.html").write_text('<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0; url=/"><link rel="canonical" href="https://tristans-website.com/"><title>Tristan Merson</title></head><body><main><h1>Tristan Merson</h1><p><a href="/">Visit the homepage</a>.</p></main></body></html>', encoding="utf-8")
print(f"Built {len(PAGES)} policy pages and retired legacy policy/SMS pages.")
